using UnityEngine;
using System.Collections;

public class School : BuildingTicker
{
		private int enviroDamage = 9;
		private int materialsBuild = 10;
		private double bonus = .15; 		//increases food generated by all by 15%
	
	public override void tick (Clock c)
		{
				//c.eatFood (upkeep);
				//c.spendGold (enviormentDamage);
				c.ruinEnvironment (enviroDamage);
		}

	
	public override bool canCollideWith (GameObject other){
		
		if (other.tag.Equals (Tags.Built))
			return false;
		
		
		if (other.name != "Trees" && other.name != "Mountain" && other.name != "Water" && other.name != "Fish")
			return true;

		return false;
	}
}
